"""Generate the original, non-looping metronome SF2 (Python standard library).

The generated binary is checked in; building/running the player needs no Python.
All samples are procedural, with no third-party recordings.
"""
from pathlib import Path
import math
import random
import struct

def chunk(tag, data):
    # SF2 requires even chunk sizes (including string terminators/padding).
    data += b"\0" * (len(data) % 2)
    return tag.encode("ascii") + struct.pack("<I", len(data)) + data

def listing(kind, chunks):
    return chunk("LIST", kind.encode("ascii") + b"".join(chunks))

def name(value):
    return value.encode("ascii")[:20].ljust(20, b"\0")

def generate():
    rate = 44100
    pcm = []
    headers = []
    rng = random.Random(20260915)
    for label, key, frequency, amplitude in [
        ("Downbeat", 60, 1900, 0.43), ("Beat", 61, 1250, 0.32)
    ]:
        start = len(pcm)
        length = int(rate * 0.06)
        for i in range(length):
            t = i / rate
            attack = min(1, i / 16)
            tail = min(1, (length - 1 - i) / 64)
            wave = (0.8 * math.sin(2 * math.pi * frequency * t)
                    + 0.14 * math.sin(2 * math.pi * frequency * 1.71 * t)
                    + 0.06 * rng.uniform(-1, 1))
            pcm.append(round(32767 * amplitude * wave * attack * tail * math.exp(-t / 0.009)))
        end = len(pcm)
        pcm.extend([0] * 46)
        headers.append(name(label) + struct.pack("<IIIIIBbHH", start, end, start + 8,
                                                 end - 8, rate, key, 0, 0, 1))
    headers.append(name("EOS") + bytes(26))
    # Key range must precede other generators; sampleID is last in a local zone.
    generators = []
    bags = []
    for sample, key in enumerate((60, 61)):
        bags.append(struct.pack("<HH", len(generators), 0))
        zone = [(43, key | key << 8), (58, key), (56, 0),
                (33, -12000), (34, -12000), (35, -12000),
                (36, -12000), (37, 0), (38, -6000), (54, 0), (53, sample)]
        generators.extend(struct.pack("<HH", op, value & 0xffff) for op, value in zone)
    bags.append(struct.pack("<HH", len(generators), 0))
    generators.append(bytes(4))
    phdr = name("Internal click") + struct.pack("<HHHIII", 127, 128, 0, 0, 0, 0)
    phdr += name("EOP") + struct.pack("<HHHIII", 0, 0, 1, 0, 0, 0)
    pdta = listing("pdta", [
        chunk("phdr", phdr), chunk("pbag", struct.pack("<HHHH", 0, 0, 1, 0)),
        chunk("pmod", bytes(10)), chunk("pgen", struct.pack("<HHHH", 41, 0, 0, 0)),
        chunk("inst", name("Clicks") + struct.pack("<H", 0) + name("EOI") + struct.pack("<H", 2)),
        chunk("ibag", b"".join(bags)), chunk("imod", bytes(10)),
        chunk("igen", b"".join(generators)), chunk("shdr", b"".join(headers))
    ])
    info = listing("INFO", [
        chunk("ifil", struct.pack("<HH", 2, 1)), chunk("isng", b"EMU8000\0"),
        chunk("INAM", b"MidiPlay internal metronome\0"),
        chunk("ICMT", b"Original procedural clicks; generated by scripts/generate-metronome-soundfont.py\0")
    ])
    sdta = listing("sdta", [chunk("smpl", struct.pack("<" + "h" * len(pcm), *pcm))])
    return chunk("RIFF", b"sfbk" + info + sdta + pdta)

if __name__ == "__main__":
    target = Path(__file__).resolve().parents[1] / "assets" / "metronome.sf2"
    target.write_bytes(generate())
    print(f"{target}: {target.stat().st_size} bytes")
